services:
  frontend:
    build:
      context: ./frontend
    container_name: todotask-frontend
    restart: always
    ports:
      - "3000:80"
    volumes:
      - "C:/Users/WEFIX HERE/IdeaProjects/todotask-backend/nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - todo-network

  app:
    build:
      context: .
    container_name: todotask-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/todotask?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - todo-network

  mysql-db:
    image: mysql:5.7
    container_name: mysql-container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todotask
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network

volumes:
  mysql-data:

networks:
  todo-network:
    driver: bridge
